name: eesup_dart_frog
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.0.0
  get_it: ^7.6.6
  dartz: ^0.10.1
  envied: ^0.5.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  supabase: ^2.0.3
  dio: ^5.4.0
  crypto: ^3.0.3

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  flutter_lints: ^3.0.1
  mockito: ^5.4.3
  build_runner: ^2.4.7
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1
  envied_generator: ^0.5.2


flutter:
  assets:
    - .env
    - .env.dev