name: eesup_frontend

packages:
   - apps/**
   - features
   - packages/**

scripts:
  analyze:
    exec: dart analyze
  format:
    description: Format code
    exec: dart format --set-exit-if-changed .
  fresh:
    exec: flutter clean && dart pub get
    description: Cleans and gets dependencies
  pg:
    exec: dart pub get
    description: Gets dependencies
  cl:
    exec: flutter clean
    description: Clean flutter project
  br:
    exec: dart pub run build_runner build --delete-conflicting-outputs
  test:
    exec: dart test
    description: Run tests
  eesup_dev:
    exec: flutter run -t apps/eesup/lib/main_dev.dart