// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/material.dart';

/// [IconlyBroken] for style Broken Icons
///
/// List Iconly Broken
///
class IconlyBroken {
  IconlyBroken._();

  static const IconData user2 = IconData(0xe000, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData user3 = IconData(0xe001, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData activity = IconData(0xe002, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData addUser = IconData(0xe003, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData arrowDown2 = IconData(0xe004, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData arrowDown3 = IconData(0xe005, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData arrowDownCircle = IconData(0xe006, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData arrowDownSquare = IconData(0xe007, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData arrowDown = IconData(0xe008, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData arrowLeft2 = IconData(0xe009, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData arrowLeft3 = IconData(0xe00a, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData arrowLeftCircle = IconData(0xe00b, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData arrowLeftSquare = IconData(0xe00c, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData arrowLeft = IconData(0xe00d, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData arrowRight2 = IconData(0xe00e, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData arrowRight3 = IconData(0xe00f, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData arrowRightCircle = IconData(0xe010, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData arrowRightSquare = IconData(0xe011, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData arrowRight = IconData(0xe012, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData arrowUp2 = IconData(0xe013, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData arrowUp3 = IconData(0xe014, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData arrowUpCircle = IconData(0xe015, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData arrowUpSquare = IconData(0xe016, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData arrowUp = IconData(0xe017, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData bag2 = IconData(0xe018, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData bag = IconData(0xe019, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData bookmark = IconData(0xe01a, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData buy = IconData(0xe01b, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData calendar = IconData(0xe01c, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData callMissed = IconData(0xe01d, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData callSilent = IconData(0xe01e, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData call = IconData(0xe01f, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData calling = IconData(0xe020, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData camera = IconData(0xe021, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData category = IconData(0xe022, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData chart = IconData(0xe023, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData chat = IconData(0xe024, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData closeSquare = IconData(0xe025, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData danger = IconData(0xe026, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData delete = IconData(0xe027, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData discount = IconData(0xe028, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData discovery = IconData(0xe029, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData document = IconData(0xe02a, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData download = IconData(0xe02b, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData editSquare = IconData(0xe02c, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData edit = IconData(0xe02d, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData filter2 = IconData(0xe02e, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData filter = IconData(0xe02f, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData folder = IconData(0xe030, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData game = IconData(0xe031, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData graph = IconData(0xe032, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData heart = IconData(0xe033, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData hide = IconData(0xe034, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData home = IconData(0xe035, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData image2 = IconData(0xe036, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData image = IconData(0xe037, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData infoCircle = IconData(0xe038, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData infoSquare = IconData(0xe039, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData location = IconData(0xe03a, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData lock = IconData(0xe03b, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData login = IconData(0xe03c, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData logout = IconData(0xe03d, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData message = IconData(0xe03e, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData moreCircle = IconData(0xe03f, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData moreSquare = IconData(0xe040, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData notification = IconData(0xe041, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData paperDownload = IconData(0xe042, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData paperFail = IconData(0xe043, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData paperNegative = IconData(0xe044, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData paperPlus = IconData(0xe045, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData paperUpload = IconData(0xe046, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData paper = IconData(0xe047, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData password = IconData(0xe048, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData play = IconData(0xe049, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData plus = IconData(0xe04a, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData profile = IconData(0xe04b, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData scan = IconData(0xe04c, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData search = IconData(0xe04d, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData send = IconData(0xe04e, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData setting = IconData(0xe04f, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData shieldDone = IconData(0xe050, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData shieldFail = IconData(0xe051, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData show = IconData(0xe052, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData star = IconData(0xe053, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData swap = IconData(0xe054, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData tickSquare = IconData(0xe055, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData ticketStar = IconData(0xe056, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData ticket = IconData(0xe057, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData timeCircle = IconData(0xe058, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData timeSquare = IconData(0xe059, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData unlock = IconData(0xe05a, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData upload = IconData(0xe05b, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData video = IconData(0xe05c, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData voice2 = IconData(0xe05d, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData voice = IconData(0xe05e, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData volumeDown = IconData(0xe05f, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData volumeOff = IconData(0xe060, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData volumeUp = IconData(0xe061, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData wallet = IconData(0xe062, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
  static const IconData work = IconData(0xe063, fontFamily: 'IconlyBroken', fontPackage: 'flutter_iconly');
}
