

create table "finances"."voucher" (
    "user_id" uuid,
    "parameter_id" uuid not null,
    "created_at" timestamp with time zone not null default now(),
    "balance" numeric not null,
    "value" numeric not null,
    "id" integer generated by default as identity not null
);


alter table "finances"."voucher" enable row level security;

create table "finances"."voucher_ledger" (
    "voucher_id" integer not null,
    "transaction_id" integer not null,
    "created_at" timestamp with time zone not null default now(),
    "opening_balance" numeric not null,
    "payout" numeric not null,
    "profit_share" numeric not null,
    "closing_balance" numeric not null
);


alter table "finances"."voucher_ledger" enable row level security;

create table "finances"."voucher_parameter" (
    "created_at" timestamp with time zone not null default now(),
    "period" integer not null,
    "interest" numeric not null,
    "minimum_value" numeric not null,
    "id" uuid not null default gen_random_uuid()
);


alter table "finances"."voucher_parameter" enable row level security;

CREATE UNIQUE INDEX voucher_ledger_pkey ON finances.voucher_ledger USING btree (voucher_id, transaction_id);

CREATE UNIQUE INDEX voucher_parameter_pkey ON finances.voucher_parameter USING btree (id);

CREATE UNIQUE INDEX voucher_pkey ON finances.voucher USING btree (id);

alter table "finances"."voucher" add constraint "voucher_pkey" PRIMARY KEY using index "voucher_pkey";

alter table "finances"."voucher_ledger" add constraint "voucher_ledger_pkey" PRIMARY KEY using index "voucher_ledger_pkey";

alter table "finances"."voucher_parameter" add constraint "voucher_parameter_pkey" PRIMARY KEY using index "voucher_parameter_pkey";

alter table "finances"."voucher" add constraint "finances_voucher_parameter_id_fkey" FOREIGN KEY (parameter_id) REFERENCES finances.voucher_parameter(id) ON DELETE CASCADE not valid;

alter table "finances"."voucher" validate constraint "finances_voucher_parameter_id_fkey";

alter table "finances"."voucher" add constraint "finances_voucher_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profile(user_id) ON DELETE CASCADE not valid;

alter table "finances"."voucher" validate constraint "finances_voucher_user_id_fkey";

alter table "finances"."voucher_ledger" add constraint "finances_voucher_ledger_transaction_id_fkey" FOREIGN KEY (transaction_id) REFERENCES finances.transaction(id) ON DELETE CASCADE not valid;

alter table "finances"."voucher_ledger" validate constraint "finances_voucher_ledger_transaction_id_fkey";

alter table "finances"."voucher_ledger" add constraint "finances_voucher_ledger_voucher_id_fkey" FOREIGN KEY (voucher_id) REFERENCES finances.voucher(id) ON DELETE CASCADE not valid;

alter table "finances"."voucher_ledger" validate constraint "finances_voucher_ledger_voucher_id_fkey";



grant delete on table "finances"."voucher" to "anon";

grant insert on table "finances"."voucher" to "anon";

grant references on table "finances"."voucher" to "anon";

grant select on table "finances"."voucher" to "anon";

grant trigger on table "finances"."voucher" to "anon";

grant truncate on table "finances"."voucher" to "anon";

grant update on table "finances"."voucher" to "anon";

grant delete on table "finances"."voucher" to "authenticated";

grant insert on table "finances"."voucher" to "authenticated";

grant references on table "finances"."voucher" to "authenticated";

grant select on table "finances"."voucher" to "authenticated";

grant trigger on table "finances"."voucher" to "authenticated";

grant truncate on table "finances"."voucher" to "authenticated";

grant update on table "finances"."voucher" to "authenticated";

grant delete on table "finances"."voucher" to "service_role";

grant insert on table "finances"."voucher" to "service_role";

grant references on table "finances"."voucher" to "service_role";

grant select on table "finances"."voucher" to "service_role";

grant trigger on table "finances"."voucher" to "service_role";

grant truncate on table "finances"."voucher" to "service_role";

grant update on table "finances"."voucher" to "service_role";

grant delete on table "finances"."voucher_ledger" to "anon";

grant insert on table "finances"."voucher_ledger" to "anon";

grant references on table "finances"."voucher_ledger" to "anon";

grant select on table "finances"."voucher_ledger" to "anon";

grant trigger on table "finances"."voucher_ledger" to "anon";

grant truncate on table "finances"."voucher_ledger" to "anon";

grant update on table "finances"."voucher_ledger" to "anon";

grant delete on table "finances"."voucher_ledger" to "authenticated";

grant insert on table "finances"."voucher_ledger" to "authenticated";

grant references on table "finances"."voucher_ledger" to "authenticated";

grant select on table "finances"."voucher_ledger" to "authenticated";

grant trigger on table "finances"."voucher_ledger" to "authenticated";

grant truncate on table "finances"."voucher_ledger" to "authenticated";

grant update on table "finances"."voucher_ledger" to "authenticated";

grant delete on table "finances"."voucher_ledger" to "service_role";

grant insert on table "finances"."voucher_ledger" to "service_role";

grant references on table "finances"."voucher_ledger" to "service_role";

grant select on table "finances"."voucher_ledger" to "service_role";

grant trigger on table "finances"."voucher_ledger" to "service_role";

grant truncate on table "finances"."voucher_ledger" to "service_role";

grant update on table "finances"."voucher_ledger" to "service_role";

grant delete on table "finances"."voucher_parameter" to "anon";

grant insert on table "finances"."voucher_parameter" to "anon";

grant references on table "finances"."voucher_parameter" to "anon";

grant select on table "finances"."voucher_parameter" to "anon";

grant trigger on table "finances"."voucher_parameter" to "anon";

grant truncate on table "finances"."voucher_parameter" to "anon";

grant update on table "finances"."voucher_parameter" to "anon";

grant delete on table "finances"."voucher_parameter" to "authenticated";

grant insert on table "finances"."voucher_parameter" to "authenticated";

grant references on table "finances"."voucher_parameter" to "authenticated";

grant select on table "finances"."voucher_parameter" to "authenticated";

grant trigger on table "finances"."voucher_parameter" to "authenticated";

grant truncate on table "finances"."voucher_parameter" to "authenticated";

grant update on table "finances"."voucher_parameter" to "authenticated";

grant delete on table "finances"."voucher_parameter" to "service_role";

grant insert on table "finances"."voucher_parameter" to "service_role";

grant references on table "finances"."voucher_parameter" to "service_role";

grant select on table "finances"."voucher_parameter" to "service_role";

grant trigger on table "finances"."voucher_parameter" to "service_role";

grant truncate on table "finances"."voucher_parameter" to "service_role";

grant update on table "finances"."voucher_parameter" to "service_role";

create policy "Enable access for authenticated users only"
on "finances"."voucher_parameter"
as permissive
for all
to authenticated
using (true)
with check (true);
