name: eesup_ui_library
description: "A new Flutter package project."
version: 0.0.1
publish_to: "none"

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  auto_route: ^7.8.4
  bloc: ^8.1.3
  int_phone_text_field:
    git:
      url: https://github.com/Miso-0/int_phone_text_field.git
      ref: main
  equatable: ^2.0.5
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.4
  flutter_dotenv: ^5.1.0
  get_it: ^7.6.7
  google_fonts: ^6.2.0
  onesignal_flutter: ^5.1.2
  sentry_flutter: ^7.17.0
  supabase_flutter: ^2.3.4
  dartz: ^0.10.1
  email_validator: ^2.1.17
  meta: ^1.11.0
  loader_overlay: ^4.0.0
  loading_animation_widget: ^1.2.0+4
  flutter_animated_dialog: ^2.0.1
  tab_container: ^2.0.0
  bootstrap_icons: ^1.11.3
  eesup_repository:
    path: ../../packages/eesup_repository
  eesup_data_source:
    path: ../../packages/eesup_data_sources
  flutter_iconly: ^1.0.2
  shimmer: ^3.0.0
  flutter_carousel_widget: ^2.2.0
  cached_network_image: ^3.3.1
  instapay_flutter:
    path: ../../packages/instapay_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  auto_route_generator: ^7.3.2
  flutter_launcher_icons: ^0.13.1
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  mockito: ^5.4.4


flutter:
